//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication2.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string approvalRemarks {
            get {
                return ResourceManager.GetString("approvalRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string approvedBy {
            get {
                return ResourceManager.GetString("approvedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string approvedByAccount {
            get {
                return ResourceManager.GetString("approvedByAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Image Url.
        /// </summary>
        public static string BannerImageUrl {
            get {
                return ResourceManager.GetString("BannerImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Article ID.
        /// </summary>
        public static string BaseArticleID {
            get {
                return ResourceManager.GetString("BaseArticleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Approve.
        /// </summary>
        public static string canApprove {
            get {
                return ResourceManager.GetString("canApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Edit.
        /// </summary>
        public static string canEdit {
            get {
                return ResourceManager.GetString("canEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Publish.
        /// </summary>
        public static string canPublish {
            get {
                return ResourceManager.GetString("canPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string categoryID {
            get {
                return ResourceManager.GetString("categoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string confirmnewpassword {
            get {
                return ResourceManager.GetString("confirmnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmpassword {
            get {
                return ResourceManager.GetString("confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string created_at {
            get {
                return ResourceManager.GetString("created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string createdByAccount {
            get {
                return ResourceManager.GetString("createdByAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        public static string dateApproved {
            get {
                return ResourceManager.GetString("dateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Date.
        /// </summary>
        public static string datePublished {
            get {
                return ResourceManager.GetString("datePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish End Date.
        /// </summary>
        public static string datePublishEnd {
            get {
                return ResourceManager.GetString("datePublishEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Start Date.
        /// </summary>
        public static string datePublishStart {
            get {
                return ResourceManager.GetString("datePublishStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproval Date.
        /// </summary>
        public static string dateUnapproved {
            get {
                return ResourceManager.GetString("dateUnapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (CN).
        /// </summary>
        public static string desc_cn {
            get {
                return ResourceManager.GetString("desc_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (EN).
        /// </summary>
        public static string desc_en {
            get {
                return ResourceManager.GetString("desc_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (ZH).
        /// </summary>
        public static string desc_zh {
            get {
                return ResourceManager.GetString("desc_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Notifications.
        /// </summary>
        public static string EmailNotifications {
            get {
                return ResourceManager.GetString("EmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excerpt.
        /// </summary>
        public static string Excerpt {
            get {
                return ResourceManager.GetString("Excerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excerpt (CN).
        /// </summary>
        public static string Excerpt_cn {
            get {
                return ResourceManager.GetString("Excerpt_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excerpt (EN).
        /// </summary>
        public static string Excerpt_en {
            get {
                return ResourceManager.GetString("Excerpt_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excerpt (ZH).
        /// </summary>
        public static string Excerpt_zh {
            get {
                return ResourceManager.GetString("Excerpt_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string forgotpassword {
            get {
                return ResourceManager.GetString("forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password History.
        /// </summary>
        public static string historyPasswords {
            get {
                return ResourceManager.GetString("historyPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Path.
        /// </summary>
        public static string imagePath {
            get {
                return ResourceManager.GetString("imagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string isActive {
            get {
                return ResourceManager.GetString("isActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string isApproved {
            get {
                return ResourceManager.GetString("isApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article List.
        /// </summary>
        public static string isArticleList {
            get {
                return ResourceManager.GetString("isArticleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Page.
        /// </summary>
        public static string isContentPage {
            get {
                return ResourceManager.GetString("isContentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string isEnabled {
            get {
                return ResourceManager.GetString("isEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen.
        /// </summary>
        public static string isFrozen {
            get {
                return ResourceManager.GetString("isFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string isPublished {
            get {
                return ResourceManager.GetString("isPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string isRequestingApproval {
            get {
                return ResourceManager.GetString("isRequestingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved.
        /// </summary>
        public static string isUnapproved {
            get {
                return ResourceManager.GetString("isUnapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to Members.
        /// </summary>
        public static string isVisibleToMembersOnly {
            get {
                return ResourceManager.GetString("isVisibleToMembersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to Traders.
        /// </summary>
        public static string isVisibleToTradingOnly {
            get {
                return ResourceManager.GetString("isVisibleToTradingOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to Visitors.
        /// </summary>
        public static string isVisibleToVisitorOnly {
            get {
                return ResourceManager.GetString("isVisibleToVisitorOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit or delete this article as it is already submitted before..
        /// </summary>
        public static string itemisfrozen {
            get {
                return ResourceManager.GetString("itemisfrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        public static string itemnotfound {
            get {
                return ResourceManager.GetString("itemnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords (CN).
        /// </summary>
        public static string Keywords_cn {
            get {
                return ResourceManager.GetString("Keywords_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords (EN).
        /// </summary>
        public static string Keywords_en {
            get {
                return ResourceManager.GetString("Keywords_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords (ZH).
        /// </summary>
        public static string Keywords_zh {
            get {
                return ResourceManager.GetString("Keywords_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login At.
        /// </summary>
        public static string lastlogin {
            get {
                return ResourceManager.GetString("lastlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Modified At.
        /// </summary>
        public static string lastPasswordModifiedAt {
            get {
                return ResourceManager.GetString("lastPasswordModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Fails.
        /// </summary>
        public static string loginfails {
            get {
                return ResourceManager.GetString("loginfails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data.
        /// </summary>
        public static string MetaData {
            get {
                return ResourceManager.GetString("MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaData (CN).
        /// </summary>
        public static string MetaData_cn {
            get {
                return ResourceManager.GetString("MetaData_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaData (EN).
        /// </summary>
        public static string MetaData_en {
            get {
                return ResourceManager.GetString("MetaData_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaData (ZH).
        /// </summary>
        public static string MetaData_zh {
            get {
                return ResourceManager.GetString("MetaData_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords.
        /// </summary>
        public static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaKeywords (CN).
        /// </summary>
        public static string MetaKeywords_cn {
            get {
                return ResourceManager.GetString("MetaKeywords_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaKeywords (EN).
        /// </summary>
        public static string MetaKeywords_en {
            get {
                return ResourceManager.GetString("MetaKeywords_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaKeywords (ZH).
        /// </summary>
        public static string MetaKeywords_zh {
            get {
                return ResourceManager.GetString("MetaKeywords_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified At.
        /// </summary>
        public static string modified_at {
            get {
                return ResourceManager.GetString("modified_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (CN).
        /// </summary>
        public static string name_cn {
            get {
                return ResourceManager.GetString("name_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (EN).
        /// </summary>
        public static string name_en {
            get {
                return ResourceManager.GetString("name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (ZH).
        /// </summary>
        public static string name_zh {
            get {
                return ResourceManager.GetString("name_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to change password.
        /// </summary>
        public static string needschangepassword {
            get {
                return ResourceManager.GetString("needschangepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string newpassword {
            get {
                return ResourceManager.GetString("newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string oldpassword {
            get {
                return ResourceManager.GetString("oldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        public static string parentItemID {
            get {
                return ResourceManager.GetString("parentItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published By.
        /// </summary>
        public static string publishedBy {
            get {
                return ResourceManager.GetString("publishedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published By.
        /// </summary>
        public static string publishedByAccount {
            get {
                return ResourceManager.GetString("publishedByAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
